### ISSUE TITLE
Make tracking all custom content types the default?

### ISSUE THREAD

**Issue by joshuarrrr** [Parsely/wp-parsely#100]
When we introduced the setting for choosing to track or not track different custom content types, the defaults of just tracking pages and posts may have actually removed tracking from existing custom content (such as Parse.ly's podcast blog). Should we track all pages and content by default?

cc @hbbtstar

**Comment by GaryJones** [comment]
This probably needs some discussion - there are plenty of custom post types that should not be included by default, even the `public` ones. 

But, if there is going to be a change in behaviour, then it should be done in a major release, since it will require action for customers to exclude ones they don't want tracked.

**Comment by acicovic** [comment]
Personally, I think that enabling such a behavior could be risky. I'd rather leave everything disabled by default and give the user a conscious choice, rather than risking to enable something that shouldn't be enabled.
