### ISSUE TITLE
Improve plugin settings UI

### ISSUE THREAD

**Issue by chriszarate** [Parsely/wp-parsely#1196]
## Is your feature request related to a problem?

The UX of the plugin settings page needs improvement.

## Describe the solution you'd like

- The "Metadata format" option is currently implemented as a drop-down, even though there are only two options. This field is better implemented as a radio button, which gives better visibility into the available options.
- There are multiple "Yes / No" radio buttons that are difficult to parse as yes / no questions. Instead, present two options with descriptions inline. For example, "Use Top-Level Categories for Section" could be better represented as "Top-Level Categories" with two options describing the different behavior.

**Comment by danielabloch** [comment]
Copy for Yes/No radio buttons

**Use Top-Level Categories for Section**
- Yes, the plugin should use the first category assigned to a post as the Section name.
- No, the plugin should not use the first category assigned to a post as the Section name.

Example: if you select Yes, a post to News > National > Florida will use "News" for the Section name, not "Florida". 

**Add Categories to Tags**
- Yes, add all assigned categories and taxonomies to my tags.
- No, do not add all assigned categories and taxonomies to my tags.

Example: if you select Yes, then a post that has been assigned the categories "Business/Tech" and "Business/Social" will automatically include "Business/Tech" and "Business/Social" as tags, too.

**Lowercase All Tags**
- Yes, I want the plugin to use lowercase versions of my tags to correct for potential misspellings.
- No, I do not want the plugin to use lowercase versions of my tags to correct for potential misspellings.

**Force HTTPS Canonicals**
- Yes, use https for canonical URLs by default.
- No, do not use https for canonical URLs by default. 

Note: the plugin uses http by default. The default is fine for most publishers. It is unlikely you'll have to change this setting unless directed to do so by Parse.ly support.

**Comment by acicovic** [comment]
@danielabloch thank you for the preparatory work, as this makes things easier for us. I have not looked into everything in detail, but whoever starts working on this will come back with questions if needed.

FYI, a remark concerning this bit:

> Add these two sections to the main screen instead of hiding them in Screen Options. 
> <img width="1165" alt="screen-options-hidden" src="https://user-images.githubusercontent.com/88679146/204564484-75c4b008-15c9-499c-9fa3-68b230134d69.png">

This is not possible, thus the feature request to [add tabs to the options page](https://github.com/Parsely/wp-parsely/issues/939) which we should consider in the future as a broader and more in-depth revamp of the settings page.

**Comment by danielabloch** [comment]
Thanks @acicovic - to clean up the asks on this ticket, I've deleted that comment and created a new request about emailing/automation specifically: https://github.com/Parsely/wp-parsely/issues/1222

**Comment by acicovic** [comment]
@danielabloch, is this my impression, or was there additional info about radios on other sections? They might got deleted whe you removed the comment.

**Comment by danielabloch** [comment]
@acicovic yes, radio buttons requested for drop-down menus where there are only two options. 

This applies to 
1. Metadata format" option
2. Use Custom Taxonomy for Section (maybe? depends on how many options there are)

**Comment by danielabloch** [comment]
Re: copy updates for the hidden screen options

**Requires Recrawl Settings**

_Use Top-Level Categories for Section_
- Yes, use the first category assigned to a post as the section name. 
- No, do not use the first category assigned to a post as the section name.

If you choose Yes, and post a story to News > National > Florida, the plugin will use "News" for the section name in your dashboard instead of "Florida".

_Use Top-Level Categories for Section_
- Yes, use lowercase versions of my tags to correct for potential misspellings.
- No, do not use lowercase versions of my tags to correct for potential misspellings.

_Force HTTPS Canonicals_
- Yes, force `https` canonical URLs by default.
- No, do not force me to use `https` canonical URLs by default. I want to use `http` instead.

Note: the plugin uses `http` by default, and this is fine for most publishers. It is unlikely you will have to change this unless directed to do so by a Parse.ly support representative.

**Advanced Settings**

_Disable Autotracking_
- Yes, disable autotracking. I do not want the tracking code to report an event as soon as the script has finished loading. I plan to implement Dynamic Tracking myself.
- No, do not disable autotracking. I want to make sure the default behavior of the tracking code is in place. The tracking code should report an event as soon as the script has finished loading.

_Wipe Parse.ly Metadata Info_
- Yes, clear all metadata information for Parse.ly posts and re-send all metadata to Parse.ly

**Comment by acicovic** [comment]
@mehmoodak I think that with the additional posts from @danielabloch, this should be all the info you need in order to go forward. When you start working on this, feel free to ask any additional questions.

**Comment by mehmoodak** [comment]
> This applies to
    1. Metadata format" option
    2. Use Custom Taxonomy for Section (maybe? depends on how many options there are)

@danielabloch not doing it for 2 because from code it seems like it can have more than two options depending on the site.

**Comment by danielabloch** [comment]
@mehmoodak that makes sense, thanks for the update.

**Comment by danielabloch** [comment]
_Track Logged-in Users_
- Yes, track logged-in users.
- No, do not track logged-in users. I do not want to see the Parse.ly tracking code on my site when browsing while logged in. 

_Disable JavaScript_
- Yes, disable JavaScript tracking. I want to use a separate system for tracking instead of the Parse.ly plugin. 
- No, do not disable JavaScript tracking. I want to the Parse.ly plugin to load the tracker.

WARNING: We highly recommend choosing "No." Disabling the JavaScript tracker will also disable the "Personalize Results" section of the recommendation widget.

**Comment by danielabloch** [comment]
Disable AMP Tracking
- Yes, disable Parse.ly tracking on AMP pages. I use a different system for JavaScript tracking on AMP pages.
- No, do not disable Parse.ly tracking on AMP pages.
