### ISSUE TITLE
Add Dashboard Widget

### ISSUE THREAD

**Issue by danielabloch** [Parsely/wp-parsely#1221]
## Is your feature request related to a problem?
wp-parsely users would benefit from additional data and content performance context within their WordPress dashboard. 

## Describe the solution you'd like
We want to add the following data points to a new Parse.ly Content Helper screen element for the wp-admin dashboard. 

**Screen element** 
As a user, I'd like the option to select the `Parse.ly Content Helper` as a screen element on my dashboard, so I can look at Parse.ly data when I log in to wp-admin. 
<img width="1291" alt="screen-element" src="https://user-images.githubusercontent.com/88679146/204659054-6d28b34e-bc20-44ed-a558-f4eaee39e6d8.png">

If the user has selected the `Parse.ly Content Helper` element, they see the following components of the screen element
<img width="626" alt="mockup" src="https://user-images.githubusercontent.com/88679146/204659148-cb8daae7-8124-45e7-90c4-fc056254cf5c.png">

**Factoids**
As a user, I would like a quick snapshot of how my content is performing today for the big, key metrics I could see in my Parse.ly dashboard:
- page views
- visitors
- ~minutes~
- avg. time
- ~soc. interactions~
- ~new posts~

**Top Posts Today (top 3)**
As a user, I would like a quick snapshot of how my top content is performing today, similar to how I could see this on the overview in the dashboard. Metrics I'd like to see:
- post title
- ~section~
- ~author~
- ~referrer~
- page views
- ~spark line~

**Comment by acicovic** [comment]
A first step to this would be to see which of this data could be **un**available through the API, or impossible to implement due to practical reasons (e.g. excessive number of API requests and consequently slowness to get the results). 

For example, I'm unsure we can currently get the spark lines data in a reasonable way. I think that verification on data availability from someone who knows the API very well would be really helpful here (but our team can dig more into this if needed).

I think that two basic questions that could be used to give us an initial trajectory are:

1. Can authors use that feature to see data from other authors, or is it strictly for their own personal posts?
2. Are we also currently considering this feature for managers that may manage multiple authors and may want to get some data out of this?

Note to our future selves: If the widget changes per user role/capabilities, then we should also need to see what happens for custom user roles/capabilities and maybe have related settings.

**Comment by danielabloch** [comment]
Checking on the API...

In the meantime, I can answer the other questions.
1. Yes, authors can see data from other authors. The top posts will show whatever the top posts are, by page views, regardless of who wrote them.
2. We are considering this for all user roles who want a quick snapshot of top performing posts and fast facts on the site performance for the day. 
3. We do not need (or want, at this stage) to consider changes per user role. That is something users can do with the Parse.ly dashboard.

**Comment by danielabloch** [comment]
I updated the original request to narrow scope of data we'll show for the day so far (pulse data).

**Factoids**
page views
visitors
avg. time

**Top 3 Posts**
post title
page views

**Comment by danielabloch** [comment]
**Notes from Dec. 15 call**
- No height restrictions. Width from 255px to 719px (including borders and padding). Smallest width here is smaller than the content helper.

**Decisions made**
- widget title: **Parse.ly Top Posts (Last 7 Days)**
- No Parse.ly logo 
- No "go to Parse.ly"
- What is this? > https://docs.parse.ly/dashboard/
- "Learn more" > https://www.parse.ly/content-analytics-dashboard/
- Top 3 factoids (page views, visitors, engage time). Width should be smaller than for posts. 
- Top 3 posts: 
-- Time range: 7 days
-- Post title and page views
-- Max 2 lines for the post title, add ellipses after that
-- Date and author as second-row metadata
-- If you’re in a year other than the current year, include the year
-- Include thumbnail images Might have problems with minimized width. 
-- No spark bars or sparklines, it’s too much lift. 
- Adopt linking as done for the Content Helper, with modification
-- if you click on a post title, it goes to post in wp-admin. 
-- If you click open on a new tab, it opens the actual post on the site. 

**Questions**
- Will it all fit? 
- Can we fit 1 2 3 for the Top 3 posts?

**Comment by danielabloch** [comment]
Site-level data is not available in the API (only post-level), so we cannot include factoids in V1 of the widget. 
"Top 3 factoids (page views, visitors, engage time). Width should be smaller than for posts." <--- out of scope for v1
