### ISSUE TITLE
Inconsistent ports in canonical URLs

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#198]
When using the plugin on an archive like author or category on a domain like `http://localhost:10024/`, then the canonical URLs show the port twice. Example output:

```json
{"@context":"http:\/\/schema.org","@type":"WebPage","headline":"Author - admin","url":"http:\/\/localhost:10024:10024\/author\/admin\/"}	
```

On a single Post, then the port doesn't appear:

```json
{"@context":"http:\/\/schema.org","@type":"NewsArticle","mainEntityOfPage":{"@type":"WebPage","@id":"http:\/\/localhost\/post-2\/"},"headline":"Post 2","url":"http:\/\/localhost\/post-2\/","thumbnailUrl":"","image":{"@type":"ImageObject","url":""},"dateCreated":"2021-04-06T23:27:26Z","datePublished":"2021-04-06T23:27:26Z","dateModified":"2021-04-06T23:27:26Z","articleSection":"Uncategorized","author":[{"@type":"Person","name":"admin"}],"creator":["admin"],"publisher":{"@type":"Organization","name":"wp-parsely","logo":""},"keywords":[]}
```

On the homepage, it shows it correctly:

```json
{"@context":"http:\/\/schema.org","@type":"WebPage","headline":"wp-parsely","url":"http:\/\/localhost:10024"}
```

This suggests that the `get_current_url()` may need looking at, and tests added.

**Comment by htdat** [comment]
I am working on this issue and I have almost done the fix. However, the main struggle is that get_current_url() is a private function, which makes things hard to create tests for it. 

A workaround is to use this https://www.php.net/manual/en/class.reflectionmethod.php. This is an example https://sandro-keil.de/blog/phpunit-with-peek-and-poke-no-more-reflection/ - I will explore this path. Otherwise, we may consider use `public` for get_current_url().

**Comment by GaryJones** [comment]
I'm fine with making it public - at some point, some of this should be moved into its own class, at which point, methods will need to be public anyway.
