### ISSUE TITLE
Incorrect use of singular/plural format for period descriptions

### ISSUE THREAD

**Issue by yuliyan** [Parsely/wp-parsely#2033]
## Describe the bug
Currently, the [getPeriodDescription() utility function](https://github.com/Parsely/wp-parsely/blame/develop/src/content-helper/common/utils/constants.ts#L93-L109) is using `_n()` and the singular and plural forms to return a different string based on the amount of time, i.e. 1 or more than 1.

However, in some languages the singular form can be used for numbers other than 1. For example, in Russian numbers like 21, 31, etc. would also use the singular form, resulting in, for example, `Last 21 Hours` returning the translation for `Last Hour`.

If you would like to use a special case for `[1] Hour/Minute/Day`, check for it specifically:

```js
if ( timeValue === 1 ) {
	__( 'Last Minute', 'wp-parsely' );
} else {
	_n( 'Last %1$d Minute', 'Last %1$d Minutes', timeValue, 'wp-parsely' )
}
```

## Additional context
Please refer to https://codex.wordpress.org/I18n_for_WordPress_Developers#Plurals for more detailed examplanation.

**Comment by acicovic** [comment]
Hello @yuliyan, thanks for reporting this. We'll definitely look into it as soon as possible 🙂

**Comment by acicovic** [comment]
Additional feedback by @GaryJones

> The singular strings around "Last Day", "Last Minute" etc. are wrong.
Singular !== 1.
In Russian, I think it's 1, 21, 31 etc. all use the "singular" form. If you're providing the single and plural form, they should both have the count placeholder or not.
If you specifically mean 1, then don't offer a pluralisation, since 1 === 1 in any language :smile:

![image](https://github.com/Parsely/wp-parsely/assets/23142906/d9cb0589-1744-4c24-a596-1168c2edb3ab)

> I think a string like "-" also may not need to be translatable, or at least needs a translator comment to signify what's it's meant for.

![image](https://github.com/Parsely/wp-parsely/assets/23142906/aba146ab-f4e4-4b20-9639-013e2755e1e6)

> Please use VoiceOver to find out how this "<< Previous" string (same for "Next >>") will be read out to screen reader users (Hint: don't use characters in strings to indicate a directionality that only sighted users would perceive).

![image](https://github.com/Parsely/wp-parsely/assets/23142906/e7a677ef-ab88-4d2d-bd85-27538f32cc68)
