### ISSUE TITLE
Move JS Build Section to CONTRIBUTING.md, remove DEVELOP.md file, add ISSUE_TEMPLATE/release-template.md

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#212]
We've changed our workflow around releases and we should capture that so when it's release time, it's as simple as possible to follow the steps.

Discussion: around p1618354624331300-slack-C01MHPS2T4J

**Comment by jblz** [comment]
@mikeyarce You took point on the last release.  Can you please grab this one?

Also, should we consider changing the name to `CONTRIBUTING.md`? I see that much more often than `DEVELOP.md`

**Comment by GaryJones** [comment]
> Also, should we consider changing the name to `CONTRIBUTING.md`? I see that much more often than `DEVELOP.md`

That's because `CONTRIBUTING.md` has a [special significance](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) in GitHub, as if the file is present, it adds links to it when opening Issues, for instance (here along with two other special files):

<img width="366" alt="Screenshot 2021-05-04 at 21 24 00" src="https://user-images.githubusercontent.com/88371/117065286-3766af80-ad1f-11eb-8d51-a1419634a4da.png">

However, I would consider the Contributing file to be more aimed at the wider audience of those opening issues, and PRs - not those few of us who are doing the releases. A contributor shouldn't need to know or care how we do a release.

In terms of having a list of things that need to be done, we can instead add an issue template just for releases - see https://github.com/Automattic/VIP-Coding-Standards/blob/develop/.github/ISSUE_TEMPLATE/release-template.md as an example, or just leave the release steps in `DEVELOP.md` or `RELEASE_STEPS.md`, and have `CONTRIBUTING.md` more focused on what are the day-to-day knowledge that contributors should have ([example](https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/.github/CONTRIBUTING.md)), such as coding standards, how to run tests, which branches to open PR's against, what versions of PHP, WP and other dependencies we use, etc.

**Comment by jblz** [comment]
Fixed by #296
