### ISSUE TITLE
Smart Linking: Prevent insertion of duplicate links

### ISSUE THREAD

**Issue by acicovic** [Parsely/wp-parsely#2476]
## Is your feature request related to a problem?
Our API back-end is markup/link agnostic. As such, when we use the Smart Linking feature multiple times on a post or Block, it is possible that a given URL could be inserted multiple times. In my own testing, I was able to insert the same URL 3 times in a paragraph block.

## Describe the solution you'd like
We probably don't want this to be happening, especially in the same block. And we probably shouldn't have the same link in a post more than 2 times. When we get the results from the API, we could check if the given URL is already present in the post or block, and not include it in the results if this is the case.

**Comment by arthur-st** [comment]
Since the plugin sends content to the API in plain text format, the API is not aware of links that exist in the content.

To exclude links that already exist in the content from being suggested by Smart Linking, you can use the `url_exclusion_list` parameter that was implemented for preventing self-referencing of content being edited. Architecturally, putting 1, 10, or 50 links into that should be equally fine.

One area of concern would be if the plugin can or cannot get canonical URLs for all links in question. If that is not possible, then we'll need to implement a URL alias resolver in the API. We can only run this from the main infrastructure stack, which means that such a project might get blocked for an iteration or two by our pod waiting on the Platform pod to tell us that they're ready to receive the Suggestions API infrastructure migration.

**Comment by acicovic** [comment]
For various technical reasons, this is on the plugin side as @arthur-st mentioned. @vaurdan will be working on this, so I'll assign this ticket to him.
