### ISSUE TITLE
Document new minimums for 3.0.0

### ISSUE THREAD

**Issue by GaryJones** [Parsely/wp-parsely#390]
## Is your feature request related to a problem?
v3.0.0 of the plugin will have higher minimum supported version of PHP and WP. This unlocks new syntax (like type declarations which can reduce bugs), reduces the cost of CI tests, and reduces the likelihood of behaviour variances due to using old versions of WordPress.

## Describe the solution you'd like
- [x] Decide on the new minimums. https://github.com/Parsely/wp-parsely/issues/390#issuecomment-926515494
- [x] Document them in the readme before the next release. #400
- [x] Add a dismissable note to the Parse.ly plugin settings page for administrators for any releases between now and 3.0.0 to inform them of the change. https://github.com/Parsely/wp-parsely/pull/408

## Additional context
For the 3.0.0 release, we can also increase the "Requires:" and "Requires PHP:" fields in the plugin headers, which will stop any auto-updates from happening if the requirements aren't met.

**Comment by pauarge** [comment]
Following some internal discussion, we have agreed on bumping the minimum required versions on the `3.0.0` release to:

- **PHP 7.1** (from PHP 5.6).  We want to jump to PHP 7 because we want to take advantage of type declarations and [some other syntactic sugar](https://github.com/Parsely/wp-parsely/pull/370#discussion_r708276211). This changes will make development faster and more reliable. As per the minor version, we go with 7.1 instead of 7.0 because it contains pretty much all the types we need.
- **WordPress 5.0** (from WordPress 4.0). Aside from tackling an [open issue that we already have](https://github.com/Parsely/wp-parsely/issues/381), WordPress 5.0 brought Gutenberg. We are working on supporting blocks in the plugin, so this will ease the development moving forward.
