### ISSUE TITLE
Option to maintain modifications to tracker placement

### ISSUE THREAD

**Issue by KArendt** [Parsely/wp-parsely#58]
We frequently encourage publishers who face consistent discrepancies to move our tracking code closer to GA (or similar). They can modify this in their WP instance, but every new release would undo it. 

Can we please make it an option to keep this (and other) modifications?

**Comment by hbbtstar** [comment]
this is actually a little hairier than I previously thought due to how the add_action happens in wordpress.

this might take me some time to figure out and we'd blow past 1.11's aimed-for release date, so I'm bumping this to 1.12. For anybody who wants to tackle this in the meantime, we'll have to figure out some magic related to:

https://codex.wordpress.org/Function_Reference/remove_action

and do the remove and add dance somewhere other than the plugin constructor, but I'm not 100% sure how to keep all this functioning smoothly at present.

**Comment by davisshaver** [comment]
@KArendt could you describe in more detail what workaround you are using currently?

**Comment by joshuarrrr** [comment]
@KArendt I think we're going to prioritize https://github.com/Parsely/wp-parsely/issues/82 first, and I think it may eliminate much of the need for this change. But there still may be legitimate needs for this, so I'm going to leave it open.

**Comment by GaryJones** [comment]
After feedback from @KArendt, it seems that whatever modification there was is lost to time. 

Still, it would be worth taking a look to see where the GA plugin adds its code and where Parse.ly adds its code in the wp_head, and to try and make them as close as possible, within the constraints that there are, or at least to document it for future knowledge.

**Comment by acicovic** [comment]
This doesn't seem to be a thing anymore. I asked Parse.ly support pointing to this issue and this is what I got as a response:

> It's not something we encounter that often now. It's been quite a while since we've recommended someone move the tracker elsewhere in the code.

So I'll close this. We can always reopen or create a new issue if this starts reoccurring.
