### ISSUE TITLE
Provide a mechanism to granularly unhook plugin features via callable reference

### ISSUE THREAD

**Issue by jblz** [Parsely/wp-parsely#618]
## Is your feature request related to a problem?

Yes. As discussed in https://github.com/Parsely/web/issues/12595#issuecomment-1021266645 & p1643122613124800-slack-C01MHPS2T4J, we do not provide a reference to unhook our functions from various actions and filters without manually inspecting the `$wp_filters` global.

For example, the `Admin_Bar` UI class is [instantiated in a function-local variable](https://github.com/Parsely/wp-parsely/blob/296e92fe77bd8859be0a886a704aac3c2e9ad2e9/wp-parsely.php#L68-L69) and then [enqueues an instance method](https://github.com/Parsely/wp-parsely/blob/296e92fe77bd8859be0a886a704aac3c2e9ad2e9/src/UI/class-admin-bar.php#L48) to do its work.

In the event this needs to get unhooked, there aren't a lot of robust options we can or should support.

e.g. this is the best I've been able to come up with on a cursory attempt (hooked in after the plugin inits and before the underlying functionality is dequeued):

```
+function remove_admin_bar_filter_function(): void {
+       global $wp_filter;
+
+       $queue = $wp_filter['admin_bar_menu']->callbacks[201] ?? [];
+
+       foreach ( $queue as $key => $item ) {
+               if (
+                       is_a( ( $item['function'][0] ?? null ), 'Parsely\UI\Admin_Bar' ) &&
+                       'admin_bar_parsely_stats_button' === $item['function'][1] ?? ''
+               ) {
+                       remove_action( 'admin_bar_menu', $key, 201 );
+                       return;
+               }
+       }
+}
```

...suboptimal.

## Describe the solution you'd like

I'm not entirely sure.

We're injecting the `$parsely` object as a dependency most (if not all) of these other classes -- perhaps we could track references in that object and expose functionality to access them and / or remove the action / filter (or something).

**Comment by pauarge** [comment]
There are many ways we can tackle this. I agree that unconditionally enqueuing things for non-core functionality of the plugin (such as the Admin Bar) might be tricky. 

I don't think the way to go is to expose object references globally, though. This ties ourselves in terms of future maneuverability, since users will be expecting a very specific object structure that is going to be, by definition, public. Similarly, enqueuing and then manually dequeuing something always looked to me like a hack.

In my opinion, the best approach for this problem is to do something that we are already doing in some places: provide a filter. Given that most of our classes have a `run` method, we can provide a filter in there that gates if the class functionality is executed or not.

**Comment by acicovic** [comment]
I agree with the idea of filters, but if anyone has any objections or downsides to report, I'll be happy to hear about them.
