### ISSUE TITLE
Fatal Error occurring on site

### ISSUE THREAD

**Issue by evantwidwell** [Parsely/wp-parsely#749]
## Describe the bug

Parsely customer is experiencing a fatal error that prevented their site from loading. The text of this error is here:

[29-Mar-2022 14:50:50 UTC] PHP Fatal error: Uncaught TypeError: Argument 1 passed to Parsely\RemoteAPI\WordPress_Cache::__construct() must be an instance of WP_Object_Cache, instance of RedisCachePro\ObjectCaches\PhpRedisObjectCache given, called in /dom33009/wp-content/plugins/wp-parsely/wp-parsely.php on line 144 and defined in /dom33009/wp-content/plugins/wp-parsely/src/RemoteAPI/class-wordpress-cache.php:31
Stack trace:
[#0](https://wordpressvip.zendesk.com/agent/tickets/0) /dom33009/wp-content/plugins/wp-parsely/wp-parsely.php(144): Parsely\RemoteAPI\WordPress_Cache->__construct(Object(RedisCachePro\ObjectCaches\PhpRedisObjectCache))
[#1](https://wordpressvip.zendesk.com/agent/tickets/1) /wordpress-versions/5.8.4/wp-includes/class-wp-hook.php(303): Parsely\parsely_rest_api_init(Object(WP_REST_Server))
[#2](https://wordpressvip.zendesk.com/agent/tickets/2) /wordpress-versions/5.8.4/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
[#3](https://wordpressvip.zendesk.com/agent/tickets/3) /wordpress-versions/5.8.4/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
[#4](https://wordpressvip.zendesk.com/agent/tickets/4) /wordpress-versions/5.8.4/wp-includes/rest-api.php(537): do_action('rest_api_init', Object(WP_REST_Server))
[#5](https://wordpressvip.zendesk.com/agent/tickets/5) /wordpress-versions/5.8.4/wp-includes/rest-api.php(495) in /dom33009/wp-content/plugins/wp-parsely/src/RemoteAPI/class-wordpress-cache.php on line 31
[

Unfortunately this is all the context I have so far, I have asked for more. (environment, VIP or not, etc.) I will update when I know more.

**Comment by GaryJones** [comment]
From the file paths, it doesn’t look to be a VIP customer.

The paths indicate WP 5.8.4, and the error message means it can only be wp-parsely 3.2.0 (released this week).

- https://github.com/Parsely/wp-parsely/blob/3.2.0/wp-parsely.php#L144
- https://github.com/Parsely/wp-parsely/blob/3.2.0/src/RemoteAPI/class-wordpress-cache.php#L31

What the error message says, is that the `$GLOBALS['wp_object_cache']` is populated by a `RedisCachePro\ObjectCaches\PhpRedisObjectCache` instead of the `WP_Object_Cache` that the code was expecting.

Redis Cache Pro seems to be a premium version (https://objectcache.pro/) of https://github.com/rhubarbgroup/redis-cache. The free version doesn't appear to contain any reference to the highlighted FQCN.

The wp-memcached drop-in (that VIP uses) [populates the global](https://github.com/Automattic/wp-memcached/blob/92ed2893b316984b34a527fbda638579c8345381/object-cache.php#L82) with an instance of the WP_Object_Cache included with the drop-in.

Likewise, the redis-cache (free plugin) drop-in [does the same](https://github.com/rhubarbgroup/redis-cache/blob/25669bd27a0b171b7a92f5157bc96cf1908e3ff4/includes/object-cache.php#L219).

To be fair, the W3 Total Cache plugin [does not name the class assigned to that global](https://github.com/W3EDGE/w3-total-cache/blob/6669102996cbef3e5dd9ae453003206390477f03/wp-content/object-cache.php#L29-L30) by the expected name, so perhaps my assumption / expectation is wrong.

(If drop-ins to persistent caches aren't present, then WP will use its [own `WP_Object_Cache`](https://github.com/WordPress/WordPress/blob/11691e8207ea24341a75c52f5777f09fa888ea28/wp-includes/class-wp-object-cache.php#L24) which just stores the values in memory.)

This is where it would have been nice if WP core had created an interface that they could all have extended from, and then we type declare against that instead.

----

@tillkruss - hi! Are you able to shed some light here as to why the global `$wp_object_cache` isn't populated with an object called / extended from `WP_Object_Cache` when using Object Cache Pro? Is my assumption wrong?

----

Pending feedback from Till, one workaround would be to simply drop the type declaration on [our constructor](https://github.com/Parsely/wp-parsely/blob/3.2.0/src/RemoteAPI/class-wordpress-cache.php#L31), but that means that we can't guarantee that `$this->cache->get()` and `$this->cache->set()` will work. 

Another more favourable alternative is that we drop the type declaration, but use the `wp_cache_get()` and `wp_cache_set()` calls inside our class instead; the [docs for `WP_Object_Cache`](https://developer.wordpress.org/reference/classes/wp_object_cache/) do say not to reference the class directly, but to use the functions instead (which seem to act as the contract for which an interface would usually provide).

**Comment by tillkruss** [comment]
Correct, Object Cache Pro doesn't use the `WP_Object_Cache` class, because it ships is various kinds of caches (like [Relay](https://relaycache.com).

Users are even capable of extending the cache classes to alter behavior.

I would second dropping the type-hint from the constructor, since it's not an interface anyhow.

Using the `wp_cache_*` helpers is an option, like you mentioned, but it makes it harder to mock/test for you.

**Comment by GaryJones** [comment]
Great, thanks for the very prompt feedback, Till!

> Using the wp_cache_* helpers is an option, like you mentioned, but it makes it harder to mock/test for you.

I debated whether to suggest we scrap our `WordPress_Cache` class, but that provides the mockable wrapper for the `wp_cache_*()` functions (though we also use [BrainMonkey](https://brain-wp.github.io/BrainMonkey/docs/functions-when.html), so we can patch any functions anyway).

**Comment by tillkruss** [comment]
Yeah, and side note: each object cache plugin ships with their own `wp_cache_*()` functions typically.

**Comment by acicovic** [comment]
Hi @GaryJones and @tillkruss. Thank you so much for stepping in and providing your very useful feedback. @pauarge mentioned that we should ship a bugfix release for this today or tomorrow.

Would we agree that for now, dropping the type declaration would be the best thing to do as a quick fix, until we decide which approach would be the best?

Thanks!

**Comment by GaryJones** [comment]
Dropping the type declaration is a must. 

Since each object cache plugin comes with their own `wp_cache_*()` functions, then we would be better to use them internally in `WordPress_Cache` as well.

**Comment by pauarge** [comment]
I would try to aim at replacing the usages to safer `wp_cache_*`. I think it should be a drop-in replacement with our current calls, and we don't have that many occurrences anyway.
