### ISSUE TITLE
Clean up the settings page

### ISSUE THREAD

**Issue by msukmanowsky** [Parsely/wp-parsely#8]
We're more than a little bit text heavy on the settings page.  Much of the information is good, but we don't need it in everyone's faces all the time and some of the copy is probably too verbose.  We should migrate to using something like https://jqueryui.com/tooltip/ to show information on demand maybe.

**Comment by hbbtstar** [comment]
This is still a really good idea, but it's already a lot for one release for us to hit a realistic timeline: I'm bumping this to 1.12, which will end up being more of a polish release anyway

**Comment by joshuarrrr** [comment]
It didn't make it to 1.12, so I'm bumping to 1.13

**Comment by GaryJones** [comment]
Here's what the settings page currently looks like.

<img width="1194" alt="Screenshot 2021-03-15 at 11 13 58" src="https://user-images.githubusercontent.com/88371/111144924-9d388580-857f-11eb-8c13-3e5d60ae36df.png">

Of the 17 settings on the page, 13 of them have the "Important: ..." message below each helper text.

I think it would make sense to re-organise the page into Basic + Advanced, or some other naming that puts all of those 13 options in a section that has a single "Important: ..." at the top. This section could be collapsed by default, so that folks know that dragons lay beyond.

Maybe if one of those settings is identified to have changed, then text could appear near the Save button as an extra reminder.

Perhaps also a message could appear by the "Settings saved." alert that contact needs to be made.

Or better yet, send a message automatically?

**Comment by GaryJones** [comment]
> Of the 17 settings on the page, 13 of them have the "Important: ..." message below each helper text.

For some reason, this comes from inline JavaScript stored in `parsely-admin-header.php`, which means if JS is not available, the warning message doesn't display.

This re-iterates the benefits of splitting the admin page into Basic and Advanced sections, and adding it to the section description (in PHP, not JS).

**Comment by mikeyarce** [comment]
One thought I had was to take out some of the settings into more of an on-boarding wizard.

Many of the settings have a big impact on the initial crawling that Parse.ly does on the site and so changing the values later won't have an effect until a recrawl is done which is currently a manual process that requires a customer contacting Parse.ly to request it.

Here's how I picture it going:

1. You install Parse.ly 
2. You'll see a banner that welcomes you and says "Thanks for installing Parse.ly! Get started now to unlock your site's content potential" or something like that.
3. You're then taken through a Wizard that asks you questions like:
4. "What post types do you want to use for Blog Articles?",  "Which Post types are for static content?", "Select a main taxonomy for  your blog articles", etc.
5. Once that's done, the wizard creates a ticket for Parse.ly to crawl the site with your set options.
6. You can still change those settings later, but we move them to a different section (I like Gary's idea of "Advanced" settings ) and make it clear that changing these requires some work on our side to make sure we recrawl the site.

The benefit of this would be that we'd emphasize that these setting should be done once when you're setting Parse.ly up, and then if they need to be changed they could still find the settings under a different section and instructions on how to ask for a recrawl.
