### ISSUE TITLE
Add field "Custom taxonomies to track" to simplify setup process

### ISSUE THREAD

**Issue by davisshaver** [Parsely/wp-parsely#87]
Should look similar to:
![screen shot 2018-03-13 at 12 45 45 pm](https://user-images.githubusercontent.com/1636964/37356492-79587d7a-26bc-11e8-9076-da75ece73e71.png)

**Comment by joshuarrrr** [comment]
@davisshaver Is this to pull "tags" from other custom taxonomies?

**Comment by joshuarrrr** [comment]
ok, cool, got it.

**Comment by acicovic** [comment]
Hi,

We now have a reworked interface, which also includes custom post types when they are available:

![image](https://user-images.githubusercontent.com/23142906/163015935-948cad2c-f0a3-4598-9a47-fb739e2ddf9c.png)

I understand what is said here from a perspective of limited-height listboxes, but with the new interface I don't see much value in splitting this into two tables. As such, I'm unsure this ticket is still relevant, and maybe we can close this.

**Comment by GaryJones** [comment]
I think the request was to consider how **taxonomy term archive pages** are selected as either a Track as Post or Track as Page (or Do not track) - and not specifically related to UI decisions.

**Comment by acicovic** [comment]
Hi,

I pointed out this ticket to Parse.ly support in order to try to get more clarity. The response I got is:

> We haven't had too many requests relating to tracking custom taxonomy values. For the few we get, we usually provide the filter documentation and that suffices.

Although I haven't verified this, using a filter might not have been an option at the time this ticket was submitted.

Since this seems to be a very seldom occurrence and it can be resolved by using a filter, I would go for closing this ticket.
